
export enum Actions {
  DELETE = "Delete",
  CREATE = "Create",
  DUPLICATE = "Duplicate",
  NEW_VERSION = "Use As New Version",
  MODIFY = "Modify",
  SAVE="Save",
  PUBLISH="Publish",
  SAVE_PUBLISH="Save And Publish",
  NULL = "",
}
export enum Types {
  PROCESS="Process",
  APPS="Apps",
  NULL = "",
}

// Enums.ts
export const GlyphiconIcons = [
  "glyphicon-asterisk",
  "glyphicon-plus",
  "glyphicon-euro",
  "glyphicon-cloud",
  "glyphicon-envelope",
  "glyphicon-pencil",
  // "glyphicon-glass",
  // "glyphicon-music",
  // "glyphicon-search",
  // "glyphicon-heart",
  // "glyphicon-star",
  // "glyphicon-user",
  // "glyphicon-film",
  // "glyphicon-th-large",
  // "glyphicon-th",
  // "glyphicon-th-list",
  // "glyphicon-ok",
  // "glyphicon-remove",
  // "glyphicon-zoom-in",
  // "glyphicon-zoom-out",
  // "glyphicon-off",
  // "glyphicon-signal",
  // "glyphicon-cog",
  // "glyphicon-trash",
  // "glyphicon-home",
  // "glyphicon-lock",
  // "glyphicon-flag",
  // "glyphicon-headphones",
  // "glyphicon-volume-off",
  // "glyphicon-volume-up",
  // "glyphicon-qrcode",
  // "glyphicon-barcode",
  // "glyphicon-tag",
  // "glyphicon-tags",
  // "glyphicon-book",
  // "glyphicon-bookmark",
  // "glyphicon-print",
  // "glyphicon-camera",
  // "glyphicon-font",
  // "glyphicon-bold",
  // "glyphicon-italic",
  // "glyphicon-text-height",
  // "glyphicon-text-width",
  // "glyphicon-align-left",
  // "glyphicon-align-center",
  // "glyphicon-align-right",
  // "glyphicon-align-justify",
  // "glyphicon-list",
  // "glyphicon-indent-left",
  // "glyphicon-indent-right",
  // "glyphicon-facetime-video",
  // "glyphicon-picture",
  // "glyphicon-map-marker"
];

export const ThemeOptions = [
  { id: "theme-1", color: "#269ABC" },
  { id: "theme-2", color: "#7DA9B0" },
  { id: "theme-3", color: "#7689AB" },
  { id: "theme-4", color: "#C74E3E" },
  { id: "theme-5", color: "#FAB96C" },
   { id: "theme-6", color: "#759D4C" },
  { id: "theme-7", color: "#B1B489" },
  { id: "theme-8", color: "#A17299" },
  { id: "theme-9", color: "#696C67" },
  { id: "theme-10", color: "#CABB33" },
];
